version: '3.6'

services:
  alpine-terraform-websocketd-UUID:
    build: .
    image: hackinglab/alpine-terraform-websocketd:3.2
    volumes:
      - ./config/terraform.tfvars:/winattacklab/terraform.tfvars
    environment:
      - "websocketurl=UUID.idocker.hacking-lab.com"
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:UUID.idocker.hacking-lab.com"
      - "traefik.protocol=http"
